### ISSUE TITLE
nns_annual test case fails

### ISSUE THREAD

**Issue by poplarShift** [BoldingBruggeman/eat#10]
I'm trying to replicate the `nns_annual` testcase but it fails:

```
 ** On entry to DSYEV  parameter number  5 had an illegal value

     PDAF-ERROR(1): Problem in computation of analysis weights!!!

STOP assimilation_pdaf(): status_pdaf /= 0
```

This is from a conda install (re-installed today).
```
$ eat-gotm --version
 model(no filter program present)
 ------------------------------------------------------------------------
 GOTM:    v6.0.6-dirty (tags/v6.0.6^0 branch)
 Config:             6
 YAML:    0.1.0 (unknown branch)
 flexout: 0.1.0 (unknown branch)
 FABM:    v2.0.0-4-g62340763-dirty (master branch)
 ERSEM:  20.10-111-g2e88016-dirty (master branch)
 NetCDF:  4.9.2 of Sep  1 2023 15:18:59 $
 ------------------------------------------------------------------------
 Compiler: GNU 13.2.0
```
 Any other versions you would need to be able to help me here?

**Comment by bolding** [comment]
Is that not the same issue you have just reported?

**Comment by poplarShift** [comment]
Well sort of, but that issue was about how to do introspection/debugging, this one is about a setup that fails but is supposed to work :)

**Comment by jornbr** [comment]
The nns_annual test case is also run as part of testing on GitHub Actions. There it currently seems fine: https://github.com/BoldingBruggeman/eat/actions/runs/6785632717/job/18444384249
Could you compare the commands you run with the ones on GitHub Actions?:
```
eat-gotm-gen yaml gotm.yaml 2 -p surface/u10/scale_factor 0.2 -p surface/v10/scale_factor 0.2 -p turbulence/turb_param/k_min 0.2
mpiexec -n 1 python run.py : -n 2 eat-gotm --separate_gotm_yaml
```

**Comment by poplarShift** [comment]
Thanks for the quick reply! It boils down to me trying to simplify logs by using only one GOTM run:
```bash
mpiexec -n 1 python run.py : -n 1 eat-gotm
```
but that won't work - with `n -2 eat-gotm` it's fine.

In hindsight I could maybe have guessed this but it would have been convenient to arrive at this conclusion by flipping some debug switch in e.g. PDAF or elsewhere.

**Comment by bolding** [comment]
please see the reply from Lars

**Comment by jornbr** [comment]
I agree that a next version EAT coul check the ensemble size and quit with a clear error earlier. That will have to depend on the PDAF assimilaiton method, as the parametrised 3DVar option requires exactly 1 ensemble member, where all others want >1. But that's easy enough to implement.
