### ISSUE TITLE
Where the GOTM settings come from in the gotm.yml file?

### ISSUE THREAD

**Issue by gerbenjansen** [BoldingBruggeman/eat#2]
Hello,

From my understanding, I need to manually add descriptions of specific observations (and files containing observations) following the template from the [GOTM Wiki](https://github.com/fabm-model/fabm/wiki/GOTM#prescribing-biogeochemical-variables). However, the gotm.yml file from the [example in the EAT repository](https://github.com/BoldingBruggeman/eat/blob/main/tests/nns_annual/gotm.yaml) describes not only observations but also general information about the experiment, such as location, time, and grid. Should this data be added manually, or is it generated automatically?

**Comment by bolding** [comment]
Hello

EAT spawns a number of (almost) ordinary GOTM simulations. The requirements for these individual simulations are the same as for an ordinary GOTM simulation - and must be configured in the same way. I.e. you need gotm.yaml and fabm.yaml files to make a simulation with the configuration specified in these two files. 

You can use the GOTM executable - eat-gotm - provided with EAT to test this - i.e. run eat-gotm as a standard command line program. In fact this is the first thing you should do before doing assimilation experiments as it can be used to see if the simulation in general 'does the right thing'

There are a number of ways to generate an ensemble in EAT. That is explained in detail in the wiki.

Karsten
