### ISSUE TITLE
How to generate gotm.ytm?

### ISSUE THREAD

**Issue by gerbenjansen** [BoldingBruggeman/eat#3]
Hello,

The header of `gotm.yml` mentions, _"You can generate a configuration with just the commonly used settings with: gotm --write_yaml <OUTFILE> --detail default."_ Do I need to build GOTM from sources to configure an experiment in EAT?

**Comment by bolding** [comment]
No - a version of the GOTM executable is installed/compiled as part of the procedure described in the wiki.

On my workstation where I build EAT manually I end up with this executable  - ~/.local/bin/eat-gotm. If you have installed via conda the eat-gotm executable will be somewhere in the conda directory structure -  ~/miniconda3/envs/eat.
Try to execute 'type eat-gotm' to show where the executable is.

GOTM comes with a large number of configuration options - that might seem overwhelming at first sight. So we have introduced a system with 3 levels displayed in gotm.yaml - minimal, default and full. The settings not shown in minimal and default take default values (specified in the Fortran source code). To change any of these 'hidden' variables you need to generate a yaml file with all (full).

The GOTM executable can be run in a special way to do that - that is what is described in the header of your gotm.yaml file.

So in my case I could do:

~/.local/bin/eat-gotm --write_yaml gotm_full.yaml --detail full.

This command will read from gotm.yaml and create gotm_full.yaml

Karsten
