### ISSUE TITLE
Where does the standard deviation come from?

### ISSUE THREAD

**Issue by gerbenjansen** [BoldingBruggeman/eat#4]
Hello,

In the EAT Wiki, it states that the last column in the observation files should be the standard deviation. How is it calculated: from existing data, or is it immediately supplied with the observations?

**Comment by bolding** [comment]
Hello

Typically the standard deviation should be come from the provider of the observations. EAT would have no way of knowing that information. The SD is used to add uncertainty to the observations so they are not taken as THE TRUTH.

Karsten
