### ISSUE TITLE
Question about the format of the observations

### ISSUE THREAD

**Issue by gerbenjansen** [BoldingBruggeman/eat#5]
Hello,

There is an example of [nns_annual](https://github.com/BoldingBruggeman/eat/tree/main/tests/nns_annual) in the EAT repository. There are several _.dat_ files in this directory. Some of them (e.g. _t_prof_file.dat_, _cci_sst.dat_, ) fit the format described in the [project wiki](https://github.com/BoldingBruggeman/eat/wiki#depth-independent-variables). Other files contain a different format. The are also connected in `gotm.yaml`. For example _sst_file.dat, zeta_file.dat, meteo_file.dat_.

Which data format should I choose to use in the EAT experiment?

**Comment by jornbr** [comment]
GOTM uses two data file formats (depth-dependent, depth-independent) for forcing. These are documented [here](https://github.com/fabm-model/fabm/wiki/GOTM#depth-dependent-variables). The EAT observation file format is slightly different and described [here](https://github.com/BoldingBruggeman/eat/wiki#observations). Hope this helps!

**Comment by jornbr** [comment]
Yes, that's all correct.
