### ISSUE TITLE
Where da_variables.dat it comes from?

### ISSUE THREAD

**Issue by gerbenjansen** [BoldingBruggeman/eat#7]
Hello!

I'm figuring out how to run an experiment with assimilation of observations. At first I didn't understand which short variable name I should specify as the first argument in `experiment.add_observations("___", "file.dat")` in `run.py`.

I looked at the source code and found that the dictionary of model variables is taken from the `da_variables.dat` file (`def get_model_variables(self)`). The `da_variables.dat` file appears only when the experiment is run. Can you please tell me where it comes from?

**Comment by bolding** [comment]
As FABM is configured at run-time not until fabm.yaml is read it is possible to create a list of the FABM state variables. That is the content of da_variables.dat and the file is created by by EAT as part of initialization.
