### ISSUE TITLE
Can't get an assimilation result

### ISSUE THREAD

**Issue by gerbenjansen** [BoldingBruggeman/eat#8]
I'm trying to run an assimilation experiment on real data.
The problem is that I don't get `result_000n.nc` files. I only get `restart_000n` and `*.stdout`, `*.stderr` files.
Perhaps you can tell me right away why this is happening?

In another case, could you describe a brief instruction:
_Let's say you have observations of temperature and salinity at different depths. There are also new temperature observations that you want to assimilate._
What would your actions be?

**Comment by jornbr** [comment]
The output configuration at the end of `gotm.yaml` determines which result files will be written. The North Sea test case that comes with EAT, for instance, is configured to write `result.nc` (`result_????.nc` in ensemble mode) here:

https://github.com/BoldingBruggeman/eat/blob/main/tests/nns_annual/gotm.yaml#L531-L557

Thus, I'd suggest to review the `output` section in your `gotm.yaml` first.

As for assimilating multiple observations: you can use multiple files with observations, even for a single variable if need be. In that case, you'd just have multiple calls to `add_observations` in your run script.
