### ISSUE TITLE
debug flags or more verbose error messages/inspection

### ISSUE THREAD

**Issue by poplarShift** [BoldingBruggeman/eat#9]
I have a setup here that (more or less...) runs with one filter but not another (details below). Is there any good way to inspect what exactly is happening here (debug flag or other)?

Relatedly, this setup is giving me an entire water column of NaNs once the first assimilation step has happend - what is the best way to inspect where these NaNs come from?

Thanks in advance!

PS: For example, my setup works with
```python
import eatpy
experiment = eatpy.models.GOTM()
filter = eatpy.PDAF(eatpy.pdaf.FilterType.EnKF)
experiment.add_observations("temp", "prof_file.eat.temperature.dat")
experiment.add_observations("salt", "prof_file.eat.salinity.dat")
experiment.run(filter)
```

but when using 
```python
filter = eatpy.PDAF(eatpy.pdaf.FilterType.ESTKF)
```
I immediately get 
```
 ** On entry to DSYEV  parameter number  5 had an illegal value

     PDAF-ERROR(1): Problem in computation of analysis weights!!!

STOP assimilation_pdaf(): status_pdaf /= 0
```
but nothing more.

**Comment by bolding** [comment]
Hello

This is a message reported from within PDAF.

I'll inform Larse Nerger - the author of PDAF - about this issue. Hopefully he will know more.

Karsten

**Comment by lnerger-pdaf** [comment]
This error message appread if the ensemble size is not correctly specified. It can likely also result when you run with ensemble size=1. In this case there is no ensemble spread and the rank of the error-subspace matrix if 0 (This is then the invalid parameter number 5). Thus, please check if the ensemble size is correctly specified as >1.

**Comment by poplarShift** [comment]
Thanks @lnerger-pdaf , I just arrived at this conclusion as well. From browsing the source code it also seems there are no convenient debug flags or compiler switches that I could be setting, to e.g. verify function arguments. LAPACK was not very helpful here, not telling me what the passed value actually is.

**Comment by lnerger-pdaf** [comment]
In deed, the version of PDAF that is currently in EAT does not have such debug output. We have added such to the most recent version of PDAF, which is not yet in EAT.
